# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      - CodecentricChallengeBackend/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - CodecentricChallengeBackend/**
      - .github/workflows/backend.yml

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: CodecentricChallengeBackend

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: |
        chmod a+x ./gradlew
        ./gradlew build
